using System.Text;

namespace ROMapOverlayEditor;

public static class RAthenaExporter
{
    public static string ExportNpcs(ProjectData project)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Generated by ROMapOverlayEditor");
        sb.AppendLine($"// Project: {project.ProjectName}");
        sb.AppendLine($"// Map: {project.MapName}");
        sb.AppendLine();

        foreach (var item in project.Items.OfType<NpcPlacable>())
        {
            var map = string.IsNullOrWhiteSpace(item.MapName) ? project.MapName : item.MapName;
            var label = string.IsNullOrWhiteSpace(item.Label) ? item.ScriptName : item.Label;

            // rAthena NPC format (simple):
            // map,x,y,dir    script    Name    Sprite,{
            //     ...
            // }
            sb.AppendLine($"{map},{item.X},{item.Y},{item.Dir}\tscript\t{EscapeToken(label)}\t{EscapeToken(item.Sprite)},{{");
            foreach (var line in NormalizeLines(item.ScriptBody))
                sb.AppendLine($"\t{line}");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        return sb.ToString();
    }

    public static string ExportWarps(ProjectData project)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Generated by ROMapOverlayEditor");
        sb.AppendLine($"// Project: {project.ProjectName}");
        sb.AppendLine($"// Map: {project.MapName}");
        sb.AppendLine();

        foreach (var item in project.Items.OfType<WarpPlacable>())
        {
            var map = string.IsNullOrWhiteSpace(item.MapName) ? project.MapName : item.MapName;

            // rAthena warp format:
            // map,x,y,dir    warp    name    w,h,destmap,destx,desty
            sb.AppendLine($"{map},{item.X},{item.Y},{item.Dir}\twarp\t{EscapeToken(item.WarpName)}\t{item.W},{item.H},{EscapeToken(item.DestMap)},{item.DestX},{item.DestY}");
        }

        return sb.ToString();
    }

    private static IEnumerable<string> NormalizeLines(string text)
    {
        if (string.IsNullOrEmpty(text))
            yield break;

        var lines = text.Replace("\r\n", "\n").Replace("\r", "\n").Split('\n');
        foreach (var ln in lines)
            yield return ln;
    }

    private static string EscapeToken(string s)
    {
        // rAthena tokens typically allow underscores; avoid tabs.
        // If user uses spaces, replace with underscore for safety.
        return (s ?? "").Trim().Replace('\t', ' ').Replace(' ', '_');
    }
}
