// ═══════════════════════════════════════════════════════════════════════════════
// FILE: TowninfoExporter.cs
// PURPOSE: Exports modified town NPC data in copy-paste format (Lua, rAthena, changelog)
// ═══════════════════════════════════════════════════════════════════════════════

using System.Linq;
using System.Text;

namespace ROMapOverlayEditor;

/// <summary>Exports town NPC data for Towninfo.lub and rAthena. Output is copy-paste only.</summary>
public static class TowninfoExporter
{
    public static string ExportToLuaFormat(string mapName, IEnumerable<NpcPlacable> npcs)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"-- ═══════════════════════════════════════════════════════════════");
        sb.AppendLine($"-- Modified by ROMapOverlayEditor on {DateTime.Now:yyyy-MM-dd HH:mm}");
        sb.AppendLine($"-- Map: {mapName}");
        sb.AppendLine($"-- Paste this into Towninfo.lub, replacing the existing {mapName} block");
        sb.AppendLine($"-- ═══════════════════════════════════════════════════════════════");
        sb.AppendLine();
        sb.AppendLine($"\t{mapName} = {{");
        foreach (var npc in npcs)
        {
            int type = GetTypeFromSprite(npc.Sprite);
            sb.AppendLine($"\t\t{{ name = [=[{npc.ScriptName}]=], X = {npc.X}, Y = {npc.Y}, TYPE = {type} }},");
        }
        sb.AppendLine("\t},");
        return sb.ToString();
    }

    public static string ExportFullTowninfo(Dictionary<string, List<NpcPlacable>> mapNpcs)
    {
        var sb = new StringBuilder();
        sb.AppendLine("-- ═══════════════════════════════════════════════════════════════");
        sb.AppendLine($"-- Generated by ROMapOverlayEditor on {DateTime.Now:yyyy-MM-dd HH:mm}");
        sb.AppendLine("-- ═══════════════════════════════════════════════════════════════");
        sb.AppendLine("mapNPCInfoTable = {");
        foreach (var kvp in mapNpcs.OrderBy(k => k.Key))
        {
            sb.AppendLine($"\t{kvp.Key} = {{");
            foreach (var npc in kvp.Value)
            {
                int type = GetTypeFromSprite(npc.Sprite);
                sb.AppendLine($"\t\t{{ name = [=[{npc.ScriptName}]=], X = {npc.X}, Y = {npc.Y}, TYPE = {type} }},");
            }
            sb.AppendLine("\t},");
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    public static string ExportToRathenaFormat(string mapName, IEnumerable<NpcPlacable> npcs)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"// Generated by ROMapOverlayEditor on {DateTime.Now:yyyy-MM-dd HH:mm}");
        sb.AppendLine($"// Map: {mapName}");
        sb.AppendLine();
        foreach (var npc in npcs)
        {
            sb.AppendLine($"{mapName},{npc.X},{npc.Y},{npc.Dir}\tscript\t{npc.ScriptName}\t{npc.Sprite},{{");
            foreach (var line in npc.ScriptBody.Split('\n'))
                sb.AppendLine($"\t{line}");
            sb.AppendLine("}");
            sb.AppendLine();
        }
        return sb.ToString();
    }

    public static string GenerateChangelog(string mapName, IEnumerable<TownNpcInfo> original, IEnumerable<NpcPlacable> modified)
    {
        var sb = new StringBuilder();
        var origList = original.ToList();
        var modList = modified.ToList();
        var matched = new HashSet<Guid>();

        sb.AppendLine($"CHANGELOG: {mapName}");
        sb.AppendLine($"Generated: {DateTime.Now:yyyy-MM-dd HH:mm}");
        sb.AppendLine();

        foreach (var orig in origList)
        {
            var mod = modList.FirstOrDefault(m => m.X == orig.X && m.Y == orig.Y);
            if (mod != null)
            {
                matched.Add(mod.Id);
                int origType = orig.Type, modType = GetTypeFromSprite(mod.Sprite);
                if (orig.Name != mod.ScriptName || origType != modType)
                {
                    sb.AppendLine($"[MODIFIED] ({orig.X}, {orig.Y})");
                    sb.AppendLine($"  Original: {orig.Name} (TYPE {origType})");
                    sb.AppendLine($"  Modified: {mod.ScriptName} (TYPE {modType})");
                    sb.AppendLine();
                }
            }
            else
            {
                sb.AppendLine($"[REMOVED] ({orig.X}, {orig.Y}) - {orig.Name}");
                sb.AppendLine();
            }
        }

        foreach (var mod in modList.Where(m => !matched.Contains(m.Id)))
        {
            if (origList.All(o => o.X != mod.X || o.Y != mod.Y))
            {
                sb.AppendLine($"[ADDED] ({mod.X}, {mod.Y}) - {mod.ScriptName} (TYPE {GetTypeFromSprite(mod.Sprite)})");
                sb.AppendLine();
            }
        }

        sb.AppendLine($"Summary: {origList.Count} original, {modList.Count} modified");
        return sb.ToString();
    }

    private static int GetTypeFromSprite(string sprite)
    {
        foreach (var kvp in TowninfoImporter.TypeToSprite)
            if (kvp.Value.Equals(sprite, StringComparison.OrdinalIgnoreCase)) return (int)kvp.Key;
        return 0;
    }
}
